### ISSUE TITLE
Incorrect branch name in documentation

### ISSUE THREAD

**Issue by achanana** [cmusatyalab/steeleagle#9]
The documentation for the [backend setup](https://cmusatyalab.github.io/steeleagle/docs/quickstart/backend) states:
```
git clone git@github.com:cmusatyalab/openscout.git
cd /path/to/openscout
# Checkout the SteelEagle branch of OpenScout
git checkout steeleagle
```
The branch name should be `steel-eagle`.

**Comment by teiszler** [comment]
Fixed in #12
